// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAszWoN8Ou6E0I5scEAl_fXLpy61BjnHhc',
    appId: '1:884126258712:web:b1997f06b2964b6c87556d',
    messagingSenderId: '884126258712',
    projectId: 'my-rentify-app',
    authDomain: 'my-rentify-app.firebaseapp.com',
    storageBucket: 'my-rentify-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd2a_nq7DA4QBtBFkHWQtkcOcJX55QXis',
    appId: '1:884126258712:android:0ccdaccdebd2cc5d87556d',
    messagingSenderId: '884126258712',
    projectId: 'my-rentify-app',
    storageBucket: 'my-rentify-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDphERxRzcgOyjrorUYZ35L4YkZ8qfPbDA',
    appId: '1:884126258712:ios:c5008db1ae06a8ab87556d',
    messagingSenderId: '884126258712',
    projectId: 'my-rentify-app',
    storageBucket: 'my-rentify-app.firebasestorage.app',
    iosBundleId: 'com.example.rentify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDphERxRzcgOyjrorUYZ35L4YkZ8qfPbDA',
    appId: '1:884126258712:ios:c5008db1ae06a8ab87556d',
    messagingSenderId: '884126258712',
    projectId: 'my-rentify-app',
    storageBucket: 'my-rentify-app.firebasestorage.app',
    iosBundleId: 'com.example.rentify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAszWoN8Ou6E0I5scEAl_fXLpy61BjnHhc',
    appId: '1:884126258712:web:ee619f6552cc16e687556d',
    messagingSenderId: '884126258712',
    projectId: 'my-rentify-app',
    authDomain: 'my-rentify-app.firebaseapp.com',
    storageBucket: 'my-rentify-app.firebasestorage.app',
  );
}
